// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_wtI9mdjm-Ma6Xyf7N49h05p7bJLWdCY',
    appId: '1:441027268019:web:527d81854e08a3fe4a8fc6',
    messagingSenderId: '441027268019',
    projectId: 'todo-6bb09',
    authDomain: 'todo-6bb09.firebaseapp.com',
    storageBucket: 'todo-6bb09.appspot.com',
    measurementId: 'G-HKNCXDHGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zKtC0Aq3Rnt-8H1CSoFcq-gbyZVsj88',
    appId: '1:441027268019:android:8b9806bc7a996e3d4a8fc6',
    messagingSenderId: '441027268019',
    projectId: 'todo-6bb09',
    storageBucket: 'todo-6bb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo5BBQ9-JGitujcwp_BCx_QD06RUCQAU',
    appId: '1:441027268019:ios:c5362aa8c10d25964a8fc6',
    messagingSenderId: '441027268019',
    projectId: 'todo-6bb09',
    storageBucket: 'todo-6bb09.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCo5BBQ9-JGitujcwp_BCx_QD06RUCQAU',
    appId: '1:441027268019:ios:bb3a4a38673c8c3a4a8fc6',
    messagingSenderId: '441027268019',
    projectId: 'todo-6bb09',
    storageBucket: 'todo-6bb09.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
